### ISSUE TITLE
Validation of empty fields of Product ,on both client side and server side, is missing  

### ISSUE THREAD

**Issue by Ali-Bhatti** [bilalshahzad139/EADProject#100]
What I want to say is that system is allowing to save a product in database with empty fields like empty name , price , picture etc. Or it gives an exception of "Invalid Fields". So validation of empty fields of Product ,on both client side and server side, is missing. And I have mentioned the line at client side too.

https://github.com/bilalshahzad139/EADProject/blob/baf2a3fdf1621c13366d033988910f7b8eca7768/Src/WebPrac/Scripts/myapp.js#L14

And line at server side       https://github.com/bilalshahzad139/EADProject/blob/baf2a3fdf1621c13366d033988910f7b8eca7768/Src/WebPrac/Controllers/Product2Controller.cs#L64

**Comment by ShisuiUzumaki** [comment]
> What I want to say is that system is allowing to save a product in database with empty fields like empty name , price , picture etc. Or it gives an exception of "Invalid Fields". So validation of empty fields of Product ,on both client side and server side, is missing. And I have mentioned the line at client side too.
> 
> https://github.com/bilalshahzad139/EADProject/blob/baf2a3fdf1621c13366d033988910f7b8eca7768/Src/WebPrac/Scripts/myapp.js#L14
> 
> And line at server side
> 
> https://github.com/bilalshahzad139/EADProject/blob/baf2a3fdf1621c13366d033988910f7b8eca7768/Src/WebPrac/Controllers/Product2Controller.cs#L64

Don't worry I am going to fix it

**Comment by Ali-Bhatti** [comment]
I have fixed it

**Comment by Ali-Bhatti** [comment]
Just I have to create pull request..☺️
