### ISSUE TITLE
Missing Cancel button on feedback page

### ISSUE THREAD

**Issue by Ali-Bhatti** [bilalshahzad139/EADProject#119]
If a regular user do not want to give feedback then how can he/she close that feedback page? As I mentioned in following line:

https://github.com/bilalshahzad139/EADProject/blob/0f258741daa4bf0a08edf305e623d53be8505ed5/Src/WebPrac/Views/User/Feedback.cshtml#L37

So I will add a cancel button.

**Comment by muhammad-bilal-ali** [comment]
Cancel button will be added during Updation of feedback feature !

**Comment by Ali-Bhatti** [comment]
I have resolved it.

**Comment by muhammad-bilal-ali** [comment]
Okay so you may close this issue now

**Comment by Ali-Bhatti** [comment]
> Okay so you may close this issue now

wait until PR got accepted

**Comment by muhammad-bilal-ali** [comment]
waiting...

**Comment by muhammad-bilal-ali** [comment]
sorry to disturb again, Ali Bhai on click event (#btnCancel) kindly close the session

**Comment by muhammad-bilal-ali** [comment]
Not yet i checked 2 minutes ago.
