### ISSUE TITLE
Unable to Edit Profile Picture

### ISSUE THREAD

**Issue by Ali-Bhatti** [bilalshahzad139/EADProject#135]
@Nadia-Ahsan In update Profile Module user is unable to update his/her profile picture. And old profile picture is not displaying too. Please correct it.

**Comment by Nadia-Ahsan** [comment]
I already mentioned that  profile update is completed except profile
picture update.
It did not update it because it's was not added in your Signup page. I am
waiting that once that page will be complete then i will add 'Profile
Picture'Update feature.

**Comment by Ali-Bhatti** [comment]
It is already completed. You can try signup. And for profile picture uploading click on avatar..

**Comment by Nadia-Ahsan** [comment]
when i was working on that module, it was showing that 'login and signup is completed except profile picture' update. May be it completed after that. Ok I'll check that and update my module accordingly.

**Comment by Nadia-Ahsan** [comment]
Ok I'll check.
