### ISSUE TITLE
Client side validation of Signup and logIn

### ISSUE THREAD

**Issue by Usman-Alii** [bilalshahzad139/EADProject#25]
Input Validation

**Comment by abdurrahman-asad** [comment]
This issue is already created. Please refer to #9 .
Please talk to them to include you as an assignee if you want to work on this.
@bilalshahzad139

**Comment by MughalUsama** [comment]
@Usman-Alii  validation or testing?
Validation is done in #9 and testing in #11

**Comment by abdurrahman-asad** [comment]
I've closed this issue as its duplicate of #9

**Comment by Ali-Bhatti** [comment]
Mark it as duplicate
