### ISSUE TITLE
Product filtering or Sorting

### ISSUE THREAD

**Issue by MuhammadZain795** [bilalshahzad139/EADProject#28]
Products can be filtered on different choices like clothing, grocery etc. For this purpose we can provide different options through drop-down menu for the customer.

**Comment by A-ASAD** [comment]
Please provide some description about how sorting/filtering will work?
 @bilalshahzad139

**Comment by MughalUsama** [comment]
Will it filter products with multiple filters or only single filter at a time? @MuhammadZain795

**Comment by MuhammadZain795** [comment]
The main idea is of filtering the products on single choice but we can do with multiple choices also... @MughalUsama

**Comment by Ayesha-nadeem** [comment]
I have already created issue for product filtering by category.Please refer to issue#10.
