### ISSUE TITLE
Designing and styling of Comment System

### ISSUE THREAD

**Issue by ShisuiUzumaki** [bilalshahzad139/EADProject#33]
CSS styling and design of Comment system will be designed

**Comment by abdurrahman-asad** [comment]
Please refer to #30 . It includes designing UI for basic comment system.

**Comment by abdurrahman-asad** [comment]
Please close this or describe something that will be different? refer #30

**Comment by ShisuiUzumaki** [comment]
> Please refer to #30 . It includes designing UI for basic comment system.

This was added before your was added
