### ISSUE TITLE
Login X Signup Page (user)

### ISSUE THREAD

**Issue by nazeer013** [bilalshahzad139/EADProject#34]
this project requires a Login and Signup page which will be provided soon.

**Comment by abdurrahman-asad** [comment]
Please refer to #9 . This is already done.

**Comment by nazeer013** [comment]
can they split that issue in two parts?
i.e for User and for Server. @A-ASAD

**Comment by abdurrahman-asad** [comment]
Actually they are almost close to completion. I myself wanted to do this task.

**Comment by abdurrahman-asad** [comment]
You can further talk to them on this, if they let you work with them as an assignee.

**Comment by nazeer013** [comment]
you should have said that before closing this issue.

**Comment by abdurrahman-asad** [comment]
Sorry for that. But please go through opened issues before creating new ones. Thanks
