### ISSUE TITLE
Likes/Dislikes on  Products

### ISSUE THREAD

**Issue by Nadia-Ahsan** [bilalshahzad139/EADProject#36]
1- User will be able to give his/her response that either he/she like or dislike  the  product.
2-It will be saved in database that which user likes/dislike which product.
3-When the products will  display, their number of likes and dislikes will also be shown. 
 (This feature can be used to find rating of products.)

**Comment by nazeer013** [comment]
Kindly let me know when you complete this issue, so i will work on #78

**Comment by Nadia-Ahsan** [comment]
i'll complete soon.
