### ISSUE TITLE
Store mulitple images against a product 

### ISSUE THREAD

**Issue by Usman-Alii** [bilalshahzad139/EADProject#42]
Task: store multiple images against a product in Database
Adding picture columns in db

**Comment by Alishba-Saeed** [comment]
@Usman-Alii  You have added a table named ProductPictureNames but there is no column in the product table. Kindly tell me if there will be a pictureID/ pictureName column in the product table or not?

**Comment by Usman-Alii** [comment]
@Alishba-Saeed  No! There is no of these columns in product table. I have added ProductID in ProductPictureNames as foreign key which will help us out in the retrieval of our desired data from ProductPictureNames table.

**Comment by Alishba-Saeed** [comment]
@Usman-Alii Wouldn't it be better to add a column to the product table instead of making another table just to store an item? Because for retrieving the pictureName we have to apply join or subquery which will increase the number of database operations. Kindly enlighten. @bilalshahzad139

**Comment by bilalshahzad139** [comment]
> @Alishba-Saeed No! There is no of these columns in product table. I have added ProductID in ProductPictureNames as foreign key which will help us out in the retrieval of our desired data from ProductPictureNames table.

We should follow this approach. If we are going to have multiple images for a product, we should store them in separate table & should have ProductID in that new table as foreign key. Having images column in product table is not a scale-able solution.

**Comment by Alishba-Saeed** [comment]
Okay, sir.
