### ISSUE TITLE
Forgot Password Option

### ISSUE THREAD

**Issue by faaizsultan** [bilalshahzad139/EADProject#45]
If User Forgets his/her password.an email with verification code will be sent and can reset his password.
Dependent on #9

**Comment by Ali-Bhatti** [comment]
Have you started working on it?

**Comment by faaizsultan** [comment]
yes.

**Comment by Ali-Bhatti** [comment]
> yes.

Good, do it as soon as possible. Because as the project is growing ,there are more chances of conflicts.

**Comment by faaizsultan** [comment]
Kindly send the  temporary email you created for earlier assignment..@Ali-Bhatti

**Comment by Ali-Bhatti** [comment]
> Kindly send the  temporary email you created for earlier assignment..@Ali-Bhatti

Email: EAD.SEMorning@gmail.com
Password: SEMorning2017
Note: first 3 letters are capital.

**Comment by faaizsultan** [comment]
Thanks.

**Comment by Ali-Bhatti** [comment]
> Thanks.

Your welcome

**Comment by faaizsultan** [comment]
@Ali-Bhatti i think you should store email address as well while signing up...becuase only then i can make the functionality of resetting password..

**Comment by faaizsultan** [comment]
So please make it ASAP so i can complete this functionality..

**Comment by Ali-Bhatti** [comment]
Yes, you are write.
Just notify me when u are done making it..i am waiting.

**Comment by Ali-Bhatti** [comment]
I will replace login with email..

**Comment by faaizsultan** [comment]
> I will replace login with email..

Thanks.

**Comment by faaizsultan** [comment]
> I will replace login with email..

Just notify me when u are done with it..

**Comment by Ali-Bhatti** [comment]
> > I will replace login with email..
> 
> Just notify me when u are done with it..

Ok I will

**Comment by Ali-Bhatti** [comment]
It is done. What i did is , I replaced the "Login" with email at fornt end. Name of backend variable in which email stores is "Login" so use login as email.. Also first try to run the whole new develop branch. You will understand it better.

**Comment by faaizsultan** [comment]
Completed.
