### ISSUE TITLE
Monthly Report of Products

### ISSUE THREAD

**Issue by Nadia-Ahsan** [bilalshahzad139/EADProject#48]
On Admin Home Screen, an option will be given to generate a report of current month sold products.
 1- A report will be shown which will include: 
     1.1- How many products sold in current month.
     1.2- Total Price of Sold Products.
It will start after completion of #9

**Comment by awaisjillani2** [comment]
you've created this issue and have not assigned to anybody,so considering the requirements of this issue i find myself fit for this task so i assigned this task to myself.
If you don't have any issue then please let me know ASAP so i can work on that.
Thanks in Advance :)

**Comment by Nadia-Ahsan** [comment]
I'll work on this issue.I assigned to myself.

**Comment by awaisjillani2** [comment]
Very nice  :)
