### ISSUE TITLE
Rating system

### ISSUE THREAD

**Issue by ShisuiUzumaki** [bilalshahzad139/EADProject#50]
User will be able to rate the product

**Comment by usama4414** [comment]
On the home screen, users will see a rating panel for each product?

**Comment by abdurrahman-asad** [comment]
This issue is already created. Please refer to #40 . @bilalshahzad139

**Comment by A-ASAD** [comment]
Please close this.

**Comment by abdurrahman-asad** [comment]
Please close this issue or describe something different than #40 . @ShisuiUzumaki

**Comment by ShisuiUzumaki** [comment]
> On the home screen, users will see a rating panel for each product?

Product is provided with rating. When user enters his/her rating then overall rating will be updated

**Comment by abdurrahman-asad** [comment]
> > On the home screen, users will see a rating panel for each product?
> 
> Product is provided with rating. When user enters his/her rating then overall rating will be updated

This is all covered in #40 . Thanks for closing.
