### ISSUE TITLE
User panel

### ISSUE THREAD

**Issue by ShisuiUzumaki** [bilalshahzad139/EADProject#58]
It will show user details and optionally will allow him/her to edit them
It includes changing email address, password, name, phone number, some settings as well as an extra feature providing user with his/her order history

**Comment by abdurrahman-asad** [comment]
@ShisuiUzumaki please refer to #47 . Some functionalities are being duplicated. Please update your description.

**Comment by Nadia-Ahsan** [comment]
@ShisuiUzumaki     I am doing many of these functionalities in #47. Kindly update your issue about which other additional  functionalities you will provide?

**Comment by Nadia-Ahsan** [comment]
@ShisuiUzumaki  I will do many of these functionalities in #47. Kindly update your issue about which other additional functionalities you will provide?
