### ISSUE TITLE
Edit User's detail & previlege

### ISSUE THREAD

**Issue by usmanmurad** [bilalshahzad139/EADProject#68]
Admin can edit details of users & can create another person admin. Client side & Server side development.

**Comment by waseem015** [comment]
Can u please briefly explain Admin's rights ?

**Comment by usmanmurad** [comment]
@waseem015  Please check Entities/UserDTO's isAdmin property. I meant that Admin should be able to create someone else admin by setting that property true for that User.

**Comment by usmanmurad** [comment]
Completed and successfully merged.
