### ISSUE TITLE
Auto Suggestion in Search Box

### ISSUE THREAD

**Issue by nazeer013** [bilalshahzad139/EADProject#75]
validating #12 if it works correctly.

**Comment by abdurrahman-asad** [comment]
Please refer to #24 .

**Comment by abdurrahman-asad** [comment]
Please close this or describe something different. Thanks @nazeer013

**Comment by nazeer013** [comment]
@A-ASAD 
this issue is for checking the efficiency of  #12 and it includes less manual testing i guess. just making sure if there is better way/logic to do that

**Comment by ShisuiUzumaki** [comment]
this topic has already been dealt with #12
