### ISSUE TITLE
Design Signup and Login Pages

### ISSUE THREAD

**Issue by Ali-Bhatti** [bilalshahzad139/EADProject#9]
Signup page will contain following fields:
1. Username
2. Login
3. Password
4. Confirm Password 
5. Profile Picture 

Login Page will contain following fields:
1. Login
2. Password

Both UI and back-end will be designed.
Abdullah is making UI and I am working on back-end. 
Muhammad Ahsan is handling profile picture.

**Comment by abdurrahman-asad** [comment]
Please split the issue as per directions by sir, as its a long task.

**Comment by Ali-Bhatti** [comment]
You want to design UI?

**Comment by Usman-Alii** [comment]
Does Back-end include Input Validation of SignUp and LogIn Page ?

**Comment by abdullah-art** [comment]
Both on client side and server side there will be validation checks on input to make it more secure!

**Comment by Nadia-Ahsan** [comment]
How you are making decision that new registered user is admin or not?

**Comment by Ali-Bhatti** [comment]
One admin user is already made. So every new user will be a simple user not admin.

**Comment by nazeer013** [comment]
is there any restriction on ProfilePicture size while uploading?

**Comment by Ali-Bhatti** [comment]
I will tell you later

**Comment by Ali-Bhatti** [comment]
> is there any restriction on ProfilePicture size while uploading?

I will be maximum 4MB that browser supports.
