### ISSUE TITLE
Code clean up and Database management

### ISSUE THREAD

**Issue by ShisuiUzumaki** [bilalshahzad139/EADProject#98]
As people are making changes in code and database, its getting harder to deal with it because its creating errors so we will do our best to change code according to database changes and vice wears 
Sir this more of group work anything that will be commuted is going to be a group work through video call @bilalshahzad139

**Comment by Ali-Bhatti** [comment]
@MughalUsama correct the "Save Product" queries accordingly. Because Tables have been updated. Some columns are removed and some are added. As I mentioned below.
https://github.com/bilalshahzad139/EADProject/blob/baf2a3fdf1621c13366d033988910f7b8eca7768/Src/PMS.DAL/ProductDAO.cs#L28
If you say then I will resolve it.

**Comment by ShisuiUzumaki** [comment]
> @MughalUsama correct the "Save Product" queries accordingly. Because Tables have been updated. Some columns are removed and some are added. As I mentioned below.
> https://github.com/bilalshahzad139/EADProject/blob/baf2a3fdf1621c13366d033988910f7b8eca7768/Src/PMS.DAL/ProductDAO.cs#L28
> 
> 
> If you say then I will resolve it.

We are working on it

**Comment by MughalUsama** [comment]
@Ali-Bhatti We have Resolved exceptions! Waiting for more. 🙂

**Comment by Ali-Bhatti** [comment]
> @Ali-Bhatti We have Resolved exceptions! Waiting for more. 🙂

Means you have updated that query in this branch?

**Comment by ShisuiUzumaki** [comment]
> > @Ali-Bhatti We have Resolved exceptions! Waiting for more. 🙂
> 
> Means you have updated that query in this branch?

yes for the most part
